/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AlertAction } from './alertAction';
import { AlertNotify } from './alertNotify';
import { EventFilter } from './eventFilter';
import { IdName } from './idName';

export class AlertCreateRequest {
    /**
    * A unique name for this alert
    */
    'name'?: string | null;
    /**
    * The current state of this alert
    */
    'state'?: AlertCreateRequest.StateEnum;
    'costCentre'?: IdName;
    /**
    * The priority of this alert
    */
    'priority'?: AlertCreateRequest.PriorityEnum;
    'filter'?: EventFilter;
    /**
    * A list of users and roles that will be notified if this alert triggers.
    */
    'notify'?: Array<AlertNotify> | null;
    /**
    * A list of actions to be performed once this alert triggers.
    */
    'actions'?: Array<AlertAction> | null;
    /**
    * The client that owns this Alert
    */
    'ownerId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "AlertCreateRequest.StateEnum"
        },
        {
            "name": "costCentre",
            "baseName": "costCentre",
            "type": "IdName"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "AlertCreateRequest.PriorityEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "EventFilter"
        },
        {
            "name": "notify",
            "baseName": "notify",
            "type": "Array<AlertNotify>"
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<AlertAction>"
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AlertCreateRequest.attributeTypeMap;
    }
}

export namespace AlertCreateRequest {
    export enum StateEnum {
        Active = <any> 'active',
        Deleted = <any> 'deleted'
    }
    export enum PriorityEnum {
        Low = <any> 'low',
        Medium = <any> 'medium',
        High = <any> 'high'
    }
}
