/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AnalyticsLevels } from './analyticsLevels';

export class AnalyticsDimension {
    'dim': AnalyticsDimension.DimEnum;
    'level': number;
    'filter': Array<string>;
    'levels': AnalyticsLevels;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dim",
            "baseName": "dim",
            "type": "AnalyticsDimension.DimEnum"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "Array<string>"
        },
        {
            "name": "levels",
            "baseName": "levels",
            "type": "AnalyticsLevels"
        }    ];

    static getAttributeTypeMap() {
        return AnalyticsDimension.attributeTypeMap;
    }
}

export namespace AnalyticsDimension {
    export enum DimEnum {
        Time = <any> 'time',
        Asset = <any> 'asset',
        CostCentre = <any> 'costCentre',
        ZoneCostCentre = <any> 'zoneCostCentre',
        AssetGroup = <any> 'assetGroup',
        ZoneGroup = <any> 'zoneGroup',
        Device = <any> 'device',
        IoType = <any> 'ioType',
        Alert = <any> 'alert',
        Event = <any> 'event',
        AssetState = <any> 'assetState',
        AssetCategory0 = <any> 'assetCategory0',
        AssetCategory1 = <any> 'assetCategory1',
        AssetCategory2 = <any> 'assetCategory2',
        AssetCategory3 = <any> 'assetCategory3',
        AssetCategory4 = <any> 'assetCategory4',
        Overspeed = <any> 'overspeed',
        Shift = <any> 'shift',
        Company = <any> 'company',
        Geography = <any> 'geography',
        DeviceType = <any> 'deviceType'
    }
}
