/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AnalyticsDataSourceOptions {
    /**
    * Definition ID of the analytics report which the widget is compatible with
    */
    'definitionId': string;
    /**
    * The parameter definition string used to generate widget settings
    */
    'parameterDefinition'?: string | null;
    'parameters'?: { [key: string]: object; };
    'filters'?: { [key: string]: object; };
    /**
    * The time rollup level of the report
    */
    'rollup'?: AnalyticsDataSourceOptions.RollupEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "definitionId",
            "baseName": "definitionId",
            "type": "string"
        },
        {
            "name": "parameterDefinition",
            "baseName": "parameterDefinition",
            "type": "string"
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "rollup",
            "baseName": "rollup",
            "type": "AnalyticsDataSourceOptions.RollupEnum"
        }    ];

    static getAttributeTypeMap() {
        return AnalyticsDataSourceOptions.attributeTypeMap;
    }
}

export namespace AnalyticsDataSourceOptions {
    export enum RollupEnum {
        Hour = <any> 'hour',
        Day = <any> 'day'
    }
}
