/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdName } from './idName';

/**
* A user can geo lock an asset to a specific location, and be notified should the asset move from that location.
*/
export class AssetGeoLock {
    'user': IdName;
    /**
    * The latitude of the location (in milliarcseconds format)
    */
    'lat': number;
    /**
    * The longitude of the location (in milliarcseconds format)
    */
    'lon': number;
    /**
    * The radius of the geo-lock in kilometers
    */
    'radiusKm': number;
    /**
    * The date and time (YYYY/MM/DD HH:mm:ss) when the geolock was initiated.
    */
    'start': string;
    /**
    * The date and time (YYYY/MM/DD HH:mm:ss) when the geolock was ended.
    */
    'end': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "IdName"
        },
        {
            "name": "lat",
            "baseName": "lat",
            "type": "number"
        },
        {
            "name": "lon",
            "baseName": "lon",
            "type": "number"
        },
        {
            "name": "radiusKm",
            "baseName": "radiusKm",
            "type": "number"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "string"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AssetGeoLock.attributeTypeMap;
    }
}

