/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChartLabel } from './chartLabel';
import { ChartSeriesItem } from './chartSeriesItem';
import { ChartXAxis } from './chartXAxis';
import { ChartYAxis } from './chartYAxis';

export class ChartOptions {
    'yAxis'?: ChartYAxis;
    'xAxis'?: ChartXAxis;
    'stacked': boolean;
    'label': ChartLabel;
    'series': { [key: string]: ChartSeriesItem; };
    'dataLabels'?: boolean | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "yAxis",
            "baseName": "yAxis",
            "type": "ChartYAxis"
        },
        {
            "name": "xAxis",
            "baseName": "xAxis",
            "type": "ChartXAxis"
        },
        {
            "name": "stacked",
            "baseName": "stacked",
            "type": "boolean"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "ChartLabel"
        },
        {
            "name": "series",
            "baseName": "series",
            "type": "{ [key: string]: ChartSeriesItem; }"
        },
        {
            "name": "dataLabels",
            "baseName": "dataLabels",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ChartOptions.attributeTypeMap;
    }
}

