/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClientMeasurementUnits } from './clientMeasurementUnits';
import { CompanyAddress } from './companyAddress';
import { CompanyMessages } from './companyMessages';
import { CompanySupportDetails } from './companySupportDetails';
import { CustomFieldDefinition } from './customFieldDefinition';
import { IdNameState } from './idNameState';
import { OpenIdConnectIssuer } from './openIdConnectIssuer';
import { ThemeInfo } from './themeInfo';

export class ClientDetailsUpdateRequest {
    'theme'?: ThemeInfo;
    'address'?: CompanyAddress;
    /**
    * The default timezone for this company
    */
    'timeZoneId'?: string | null;
    'customFields'?: { [key: string]: Array<CustomFieldDefinition>; };
    /**
    * A list of custom domains to use for this company
    */
    'domains'?: Array<string> | null;
    /**
    * The default language to user for this client.
    */
    'language'?: string | null;
    'support'?: CompanySupportDetails;
    'messages'?: CompanyMessages;
    'oidc'?: { [key: string]: OpenIdConnectIssuer; };
    'emailProvider'?: IdNameState;
    'measurementUnits'?: ClientMeasurementUnits;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "theme",
            "baseName": "theme",
            "type": "ThemeInfo"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "CompanyAddress"
        },
        {
            "name": "timeZoneId",
            "baseName": "timeZoneId",
            "type": "string"
        },
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "{ [key: string]: Array<CustomFieldDefinition>; }"
        },
        {
            "name": "domains",
            "baseName": "domains",
            "type": "Array<string>"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "support",
            "baseName": "support",
            "type": "CompanySupportDetails"
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "CompanyMessages"
        },
        {
            "name": "oidc",
            "baseName": "oidc",
            "type": "{ [key: string]: OpenIdConnectIssuer; }"
        },
        {
            "name": "emailProvider",
            "baseName": "emailProvider",
            "type": "IdNameState"
        },
        {
            "name": "measurementUnits",
            "baseName": "measurementUnits",
            "type": "ClientMeasurementUnits"
        }    ];

    static getAttributeTypeMap() {
        return ClientDetailsUpdateRequest.attributeTypeMap;
    }
}

