/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdName } from './idName';
import { IdNameType } from './idNameType';

export class DashboardTemplateListItem {
    /**
    * The unique UUID for this Dashboard
    */
    'id': string;
    'owner': IdNameType;
    /**
    * The state of the entity
    */
    'state': DashboardTemplateListItem.StateEnum;
    'user': IdName;
    /**
    * The name of the dashboard.
    */
    'name': string;
    /**
    * A short description of the dashboard.
    */
    'description': string;
    /**
    * Determines if the dashboard can be added by downstream users
    */
    '_public'?: boolean | null;
    /**
    * The date the entity was last modified
    */
    'modifiedDate': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "IdNameType"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "DashboardTemplateListItem.StateEnum"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "IdName"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean"
        },
        {
            "name": "modifiedDate",
            "baseName": "modifiedDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DashboardTemplateListItem.attributeTypeMap;
    }
}

export namespace DashboardTemplateListItem {
    export enum StateEnum {
        Active = <any> 'active',
        Deleted = <any> 'deleted'
    }
}
