/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DeviceTypeAccessory } from './deviceTypeAccessory';
import { DeviceTypeFeature } from './deviceTypeFeature';
import { DeviceTypeIOCapabilities } from './deviceTypeIOCapabilities';
import { IdName } from './idName';

export class DeviceTypeCreateRequest {
    /**
    * A unique name for this entity
    */
    'name'?: string | null;
    /**
    * A short name for this device type (usually just a model number)
    */
    'shortName'?: string | null;
    'parent'?: IdName;
    /**
    * A unique tag for this entity
    */
    'tag'?: string | null;
    /**
    * The current state of the device type object
    */
    'state'?: DeviceTypeCreateRequest.StateEnum;
    'deviceProviderType'?: IdName;
    'ioCapabilities'?: DeviceTypeIOCapabilities;
    /**
    * A form definition for custom settings in this device type
    */
    'settingsDefinition'?: string | null;
    'accessories'?: { [key: string]: DeviceTypeAccessory; };
    'features'?: { [key: string]: DeviceTypeFeature; };
    'ownerId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "shortName",
            "baseName": "shortName",
            "type": "string"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "IdName"
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "DeviceTypeCreateRequest.StateEnum"
        },
        {
            "name": "deviceProviderType",
            "baseName": "deviceProviderType",
            "type": "IdName"
        },
        {
            "name": "ioCapabilities",
            "baseName": "ioCapabilities",
            "type": "DeviceTypeIOCapabilities"
        },
        {
            "name": "settingsDefinition",
            "baseName": "settingsDefinition",
            "type": "string"
        },
        {
            "name": "accessories",
            "baseName": "accessories",
            "type": "{ [key: string]: DeviceTypeAccessory; }"
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "{ [key: string]: DeviceTypeFeature; }"
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DeviceTypeCreateRequest.attributeTypeMap;
    }
}

export namespace DeviceTypeCreateRequest {
    export enum StateEnum {
        Active = <any> 'active',
        Deleted = <any> 'deleted'
    }
}
