/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DeviceTypeIOCapabilities {
    'digitalInput'?: { [key: string]: object; };
    'digitalOutput'?: { [key: string]: object; };
    'analogInput'?: { [key: string]: object; };
    'temperatureInput'?: { [key: string]: object; };
    'canInput'?: { [key: string]: object; };
    'counterInput'?: { [key: string]: object; };
    'cameraInput'?: { [key: string]: object; };
    'valueInput'?: { [key: string]: object; };
    'cachedFields'?: Array<string> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "digitalInput",
            "baseName": "digital_input",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "digitalOutput",
            "baseName": "digital_output",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "analogInput",
            "baseName": "analog_input",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "temperatureInput",
            "baseName": "temperature_input",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "canInput",
            "baseName": "can_input",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "counterInput",
            "baseName": "counter_input",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "cameraInput",
            "baseName": "camera_input",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "valueInput",
            "baseName": "value_input",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "cachedFields",
            "baseName": "cached_fields",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return DeviceTypeIOCapabilities.attributeTypeMap;
    }
}

