/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DeviceIOParameters } from './deviceIOParameters';

export class DeviceParameters {
    /**
    * The input that is used to determine when the device becomes active (ignition on for vehicles). Determines when trips are started and ended.
    */
    'activeInput'?: string | null;
    /**
    * The input that is used to start counting engine hours. This is usually the same as \'active_input\'.
    */
    'hoursInput'?: string | null;
    /**
    * The input that is used to determine when the device is idling. Defaults to \"speed\" where idling is calulated based on device speed.
    */
    'idlingInput'?: string | null;
    'io'?: DeviceIOParameters;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "activeInput",
            "baseName": "active_input",
            "type": "string"
        },
        {
            "name": "hoursInput",
            "baseName": "hours_input",
            "type": "string"
        },
        {
            "name": "idlingInput",
            "baseName": "idling_input",
            "type": "string"
        },
        {
            "name": "io",
            "baseName": "io",
            "type": "DeviceIOParameters"
        }    ];

    static getAttributeTypeMap() {
        return DeviceParameters.attributeTypeMap;
    }
}

