/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EventActorFilter } from './eventActorFilter';
import { IdName } from './idName';

export class ExportTaskUpdateRequest {
    'client'?: IdName;
    /**
    * The name of the export task
    */
    'name'?: string | null;
    /**
    * The state of the export task
    */
    'state'?: ExportTaskUpdateRequest.StateEnum;
    /**
    * The delivery method of the export tasks
    */
    'deliveryMethod'?: ExportTaskUpdateRequest.DeliveryMethodEnum;
    /**
    * The filters used to get the assets to be included in the export task
    */
    'assets'?: Array<EventActorFilter> | null;
    /**
    * The document types to include in the export task
    */
    'documentTypes'?: Array<string> | null;
    /**
    * The document layout version
    */
    'documentVersion'?: ExportTaskUpdateRequest.DocumentVersionEnum;
    'settings'?: { [key: string]: object; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "client",
            "baseName": "client",
            "type": "IdName"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "ExportTaskUpdateRequest.StateEnum"
        },
        {
            "name": "deliveryMethod",
            "baseName": "deliveryMethod",
            "type": "ExportTaskUpdateRequest.DeliveryMethodEnum"
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<EventActorFilter>"
        },
        {
            "name": "documentTypes",
            "baseName": "documentTypes",
            "type": "Array<string>"
        },
        {
            "name": "documentVersion",
            "baseName": "documentVersion",
            "type": "ExportTaskUpdateRequest.DocumentVersionEnum"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "{ [key: string]: object; }"
        }    ];

    static getAttributeTypeMap() {
        return ExportTaskUpdateRequest.attributeTypeMap;
    }
}

export namespace ExportTaskUpdateRequest {
    export enum StateEnum {
        Suspended = <any> 'suspended',
        Active = <any> 'active',
        Deleted = <any> 'deleted'
    }
    export enum DeliveryMethodEnum {
        Http = <any> 'http',
        Stream = <any> 'stream',
        Firehose = <any> 'firehose'
    }
    export enum DocumentVersionEnum {
        V1 = <any> 'v1',
        V2 = <any> 'v2'
    }
}
