/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EntityInfo } from './entityInfo';
import { IdNameType } from './idNameType';
import { MapSetLayer } from './mapSetLayer';

export class MapSetResponse {
    /**
    * The unique UUID of this entity
    */
    'id': string;
    'owner': IdNameType;
    /**
    * A unique name for this map set
    */
    'name'?: string | null;
    /**
    * One or more layers available in this map set
    */
    'layers'?: Array<MapSetLayer> | null;
    /**
    * The state of this map set
    */
    'state'?: MapSetResponse.StateEnum;
    /**
    * One or more overlays for this map set
    */
    'overlays'?: Array<MapSetLayer> | null;
    /**
    * The url to use for static maps when this map set is selected
    */
    'staticMapURL'?: string | null;
    'entity': EntityInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "IdNameType"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "layers",
            "baseName": "layers",
            "type": "Array<MapSetLayer>"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "MapSetResponse.StateEnum"
        },
        {
            "name": "overlays",
            "baseName": "overlays",
            "type": "Array<MapSetLayer>"
        },
        {
            "name": "staticMapURL",
            "baseName": "staticMapURL",
            "type": "string"
        },
        {
            "name": "entity",
            "baseName": "entity",
            "type": "EntityInfo"
        }    ];

    static getAttributeTypeMap() {
        return MapSetResponse.attributeTypeMap;
    }
}

export namespace MapSetResponse {
    export enum StateEnum {
        Active = <any> 'active',
        Deleted = <any> 'deleted'
    }
}
