/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The configuration settings for the queued report
*/
export class ReportConfig {
    /**
    * The language that this report is being generated in
    */
    'language'?: string | null;
    /**
    * The ID of the report defininition that was used to create this report
    */
    'definitionId'?: string | null;
    /**
    * The style of the report that was selected
    */
    'styleId'?: string | null;
    /**
    * The parameters that were passed to the report
    */
    'parameters'?: object | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "definitionId",
            "baseName": "definitionId",
            "type": "string"
        },
        {
            "name": "styleId",
            "baseName": "styleId",
            "type": "string"
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return ReportConfig.attributeTypeMap;
    }
}

