/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReverseGeocode {
    /**
    * Road name
    */
    'rd'?: string | null;
    /**
    * Suburb name
    */
    'sb'?: string | null;
    /**
    * Town name
    */
    'tw'?: string | null;
    /**
    * Province or state namee
    */
    'pr'?: string | null;
    /**
    * Post code
    */
    'pc'?: string | null;
    /**
    * City name
    */
    'ct'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rd",
            "baseName": "rd",
            "type": "string"
        },
        {
            "name": "sb",
            "baseName": "sb",
            "type": "string"
        },
        {
            "name": "tw",
            "baseName": "tw",
            "type": "string"
        },
        {
            "name": "pr",
            "baseName": "pr",
            "type": "string"
        },
        {
            "name": "pc",
            "baseName": "pc",
            "type": "string"
        },
        {
            "name": "ct",
            "baseName": "ct",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReverseGeocode.attributeTypeMap;
    }
}

