/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdName } from './idName';
import { IdNameType } from './idNameType';
import { Schedule } from './schedule';
import { ScheduledReportReport } from './scheduledReportReport';

export class ScheduledReportUpdateRequest {
    'user'?: IdName;
    /**
    * A unique name for this entity
    */
    'name'?: string | null;
    /**
    * The current state of this entity
    */
    'state'?: ScheduledReportUpdateRequest.StateEnum;
    /**
    * The type of scheduled report.
    */
    'scheduleType'?: ScheduledReportUpdateRequest.ScheduleTypeEnum;
    'schedule'?: Schedule;
    'reports'?: { [key: string]: ScheduledReportReport; };
    /**
    * The recipients that will receive an email with the completed reports
    */
    'recipients'?: Array<IdNameType> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "IdName"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "ScheduledReportUpdateRequest.StateEnum"
        },
        {
            "name": "scheduleType",
            "baseName": "scheduleType",
            "type": "ScheduledReportUpdateRequest.ScheduleTypeEnum"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "Schedule"
        },
        {
            "name": "reports",
            "baseName": "reports",
            "type": "{ [key: string]: ScheduledReportReport; }"
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<IdNameType>"
        }    ];

    static getAttributeTypeMap() {
        return ScheduledReportUpdateRequest.attributeTypeMap;
    }
}

export namespace ScheduledReportUpdateRequest {
    export enum StateEnum {
        Active = <any> 'active',
        Deleted = <any> 'deleted'
    }
    export enum ScheduleTypeEnum {
        Report = <any> 'report',
        Analytics = <any> 'analytics'
    }
}
