/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReportConfig } from './reportConfig';

export class ScheduledReportReport {
    /**
    * The report title as set by the user
    */
    'title'?: string | null;
    /**
    * The output format for this report
    */
    'outputFormat'?: ScheduledReportReport.OutputFormatEnum;
    'config'?: ReportConfig;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "outputFormat",
            "baseName": "outputFormat",
            "type": "ScheduledReportReport.OutputFormatEnum"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "ReportConfig"
        }    ];

    static getAttributeTypeMap() {
        return ScheduledReportReport.attributeTypeMap;
    }
}

export namespace ScheduledReportReport {
    export enum OutputFormatEnum {
        Pdf = <any> 'pdf',
        Xlsx = <any> 'xlsx',
        Xml = <any> 'xml',
        Csv = <any> 'csv',
        Raw = <any> 'raw',
        Json = <any> 'json'
    }
}
