/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SimCardUpdateRequest {
    /**
    * The serial number of the SIM card that is used to uniquely identify it.
    */
    'name'?: string | null;
    /**
    * The name of the telecommunications network.
    */
    'networkName'?: string | null;
    /**
    * The direct mobile number for this SIM card. Must be in international format starting with +.
    */
    'number'?: string | null;
    /**
    * A short description of the sim card.
    */
    'description'?: string | null;
    /**
    * The current state of the object
    */
    'state'?: SimCardUpdateRequest.StateEnum;
    'fields'?: { [key: string]: object; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "networkName",
            "baseName": "networkName",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "SimCardUpdateRequest.StateEnum"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "{ [key: string]: object; }"
        }    ];

    static getAttributeTypeMap() {
        return SimCardUpdateRequest.attributeTypeMap;
    }
}

export namespace SimCardUpdateRequest {
    export enum StateEnum {
        Inactive = <any> 'inactive',
        Active = <any> 'active',
        Suspended = <any> 'suspended',
        Deleted = <any> 'deleted'
    }
}
