/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TelemetryTrip {
    'start': string;
    'startAddress': string;
    'startLon': number;
    'startLat': number;
    'distance': number;
    'lastLon': number;
    'lastLat': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "start",
            "baseName": "start",
            "type": "string"
        },
        {
            "name": "startAddress",
            "baseName": "startAddress",
            "type": "string"
        },
        {
            "name": "startLon",
            "baseName": "startLon",
            "type": "number"
        },
        {
            "name": "startLat",
            "baseName": "startLat",
            "type": "number"
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number"
        },
        {
            "name": "lastLon",
            "baseName": "lastLon",
            "type": "number"
        },
        {
            "name": "lastLat",
            "baseName": "lastLat",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TelemetryTrip.attributeTypeMap;
    }
}

