/**
 * Fleet API Specification
 * Welcome to the Key Telematics Fleet API specification. This document outlines the REST routes and data structures returned by the  API and offers examples of usage.  The API publishes a [swagger](https://swagger.io/) specification that can be used to [generate a client library](https://github.com/swagger-api/swagger-codegen) for your language of choice.   The latest swagger file is available for download from the following link: [https://api.eu1.kt1.io/fleet/v2/swagger.json](https://api.eu1.kt1.io/fleet/v2/swagger.json)
 *
 * The version of the OpenAPI document: 2.2.8
 * Contact: support@keytelematics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Information about a logged in user session
*/
export class UserSession {
    /**
    * The unique ID of this session
    */
    'id': string;
    /**
    * The user UUID
    */
    'userId': string;
    /**
    * The ISO date when the session was started
    */
    'start': string;
    /**
    * The expiry date of the session (can be extended with token refreshes)
    */
    'expiry': string;
    /**
    * The IP address of the user that initiated or last refreshed the session
    */
    'ip': string;
    /**
    * The hostname of the front-end from which the session was created
    */
    'hostname': string;
    /**
    * The browser user agent string of the user
    */
    'agent': string;
    /**
    * A flag indicating if the session has been invalidated
    */
    'invalidated'?: boolean | null;
    /**
    * True if this session is the same session from which this request was made
    */
    'current': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "string"
        },
        {
            "name": "expiry",
            "baseName": "expiry",
            "type": "string"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "hostname",
            "baseName": "hostname",
            "type": "string"
        },
        {
            "name": "agent",
            "baseName": "agent",
            "type": "string"
        },
        {
            "name": "invalidated",
            "baseName": "invalidated",
            "type": "boolean"
        },
        {
            "name": "current",
            "baseName": "current",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UserSession.attributeTypeMap;
    }
}

