export * from './accountsApi';
import { AccountsApi } from './accountsApi';
export * from './alertsApi';
import { AlertsApi } from './alertsApi';
export * from './assetCategoriesApi';
import { AssetCategoriesApi } from './assetCategoriesApi';
export * from './assetGroupsApi';
import { AssetGroupsApi } from './assetGroupsApi';
export * from './assetRatingProfilesApi';
import { AssetRatingProfilesApi } from './assetRatingProfilesApi';
export * from './assetStateProfilesApi';
import { AssetStateProfilesApi } from './assetStateProfilesApi';
export * from './assetTagTypesApi';
import { AssetTagTypesApi } from './assetTagTypesApi';
export * from './assetTagsApi';
import { AssetTagsApi } from './assetTagsApi';
export * from './assetTypesApi';
import { AssetTypesApi } from './assetTypesApi';
export * from './assetsApi';
import { AssetsApi } from './assetsApi';
export * from './authApi';
import { AuthApi } from './authApi';
export * from './clientsApi';
import { ClientsApi } from './clientsApi';
export * from './companiesApi';
import { CompaniesApi } from './companiesApi';
export * from './companyGroupsApi';
import { CompanyGroupsApi } from './companyGroupsApi';
export * from './costCentresApi';
import { CostCentresApi } from './costCentresApi';
export * from './dashboardTemplatesApi';
import { DashboardTemplatesApi } from './dashboardTemplatesApi';
export * from './dashboardsApi';
import { DashboardsApi } from './dashboardsApi';
export * from './dataApi';
import { DataApi } from './dataApi';
export * from './deviceProviderTypesApi';
import { DeviceProviderTypesApi } from './deviceProviderTypesApi';
export * from './deviceProvidersApi';
import { DeviceProvidersApi } from './deviceProvidersApi';
export * from './deviceTypesApi';
import { DeviceTypesApi } from './deviceTypesApi';
export * from './devicesApi';
import { DevicesApi } from './devicesApi';
export * from './distributorsApi';
import { DistributorsApi } from './distributorsApi';
export * from './emailProvidersApi';
import { EmailProvidersApi } from './emailProvidersApi';
export * from './emailProvidersTypesApi';
import { EmailProvidersTypesApi } from './emailProvidersTypesApi';
export * from './entitiesApi';
import { EntitiesApi } from './entitiesApi';
export * from './exportTasksApi';
import { ExportTasksApi } from './exportTasksApi';
export * from './feedsApi';
import { FeedsApi } from './feedsApi';
export * from './healthApi';
import { HealthApi } from './healthApi';
export * from './historyApi';
import { HistoryApi } from './historyApi';
export * from './ioTypesApi';
import { IoTypesApi } from './ioTypesApi';
export * from './lookupsApi';
import { LookupsApi } from './lookupsApi';
export * from './mapApi';
import { MapApi } from './mapApi';
export * from './mapSetsApi';
import { MapSetsApi } from './mapSetsApi';
export * from './mediaApi';
import { MediaApi } from './mediaApi';
export * from './notificationsApi';
import { NotificationsApi } from './notificationsApi';
export * from './overspeedProfilesApi';
import { OverspeedProfilesApi } from './overspeedProfilesApi';
export * from './queuesApi';
import { QueuesApi } from './queuesApi';
export * from './redirectApi';
import { RedirectApi } from './redirectApi';
export * from './remindersApi';
import { RemindersApi } from './remindersApi';
export * from './reportDefinitionsApi';
import { ReportDefinitionsApi } from './reportDefinitionsApi';
export * from './reportTemplatesApi';
import { ReportTemplatesApi } from './reportTemplatesApi';
export * from './reportsApi';
import { ReportsApi } from './reportsApi';
export * from './scheduledReportsApi';
import { ScheduledReportsApi } from './scheduledReportsApi';
export * from './searchApi';
import { SearchApi } from './searchApi';
export * from './simCardsApi';
import { SimCardsApi } from './simCardsApi';
export * from './smsGatewayProvidersApi';
import { SmsGatewayProvidersApi } from './smsGatewayProvidersApi';
export * from './smsGatewayProvidersTypesApi';
import { SmsGatewayProvidersTypesApi } from './smsGatewayProvidersTypesApi';
export * from './statsApi';
import { StatsApi } from './statsApi';
export * from './tasksApi';
import { TasksApi } from './tasksApi';
export * from './themesApi';
import { ThemesApi } from './themesApi';
export * from './translateApi';
import { TranslateApi } from './translateApi';
export * from './userRolesApi';
import { UserRolesApi } from './userRolesApi';
export * from './usersApi';
import { UsersApi } from './usersApi';
export * from './vendorsApi';
import { VendorsApi } from './vendorsApi';
export * from './zoneGroupsApi';
import { ZoneGroupsApi } from './zoneGroupsApi';
export * from './zonesApi';
import { ZonesApi } from './zonesApi';
import * as http from 'http';

export class HttpError extends Error {
    constructor (public response: http.IncomingMessage, public body: any, public statusCode?: number) {
        super('HTTP request failed');
        this.name = 'HttpError';
    }
}

export { RequestFile } from '../model/models';

export const APIS = [AccountsApi, AlertsApi, AssetCategoriesApi, AssetGroupsApi, AssetRatingProfilesApi, AssetStateProfilesApi, AssetTagTypesApi, AssetTagsApi, AssetTypesApi, AssetsApi, AuthApi, ClientsApi, CompaniesApi, CompanyGroupsApi, CostCentresApi, DashboardTemplatesApi, DashboardsApi, DataApi, DeviceProviderTypesApi, DeviceProvidersApi, DeviceTypesApi, DevicesApi, DistributorsApi, EmailProvidersApi, EmailProvidersTypesApi, EntitiesApi, ExportTasksApi, FeedsApi, HealthApi, HistoryApi, IoTypesApi, LookupsApi, MapApi, MapSetsApi, MediaApi, NotificationsApi, OverspeedProfilesApi, QueuesApi, RedirectApi, RemindersApi, ReportDefinitionsApi, ReportTemplatesApi, ReportsApi, ScheduledReportsApi, SearchApi, SimCardsApi, SmsGatewayProvidersApi, SmsGatewayProvidersTypesApi, StatsApi, TasksApi, ThemesApi, TranslateApi, UserRolesApi, UsersApi, VendorsApi, ZoneGroupsApi, ZonesApi];
